appName: cartservice
appVersion: gcr.io/google-samples/microservices-demo/cartservice
appImage: v.0.2.3
appReplicas: 2
containerPort: 7070
containerEnvVars:
  - key: PORT
    value: "7070"
  - key: REDIS_ADDR
    value: "redis-cart:6379"

servicePort: 7070
