appName: frontend
appVersion: gcr.io/google-samples/microservices-demo/frontend
appImage: v.0.2.3
appReplicas: 2
containerPort: 8080
containerEnvVars:
  - key: PORT
    value: "8080"
  - key: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - key: SHIPPING_SERVICE_ADDR
    value: "shippingservice:50051"
  - key: PAYMENT_SERVICE_ADDR
    value: "paymentservice:50051"
  - key: EMAIL_SERVICE_ADDR
    value: "emailservice:5000"
  - key: CURRENCY_SERVICE_ADDR
    value: "currencyservice:7000"
  - key: CART_SERVICE_ADDR
    value: "cartservice:7070"

servicePort: 80
serviceType: LoadBalancer
