appName: productcatalogservice
appVersion: gcr.io/google-samples/microservices-demo/productcatalogservice
appImage: v.0.2.3
appReplicas: 2
containerPort: 3550
containerEnvVars:
  - key: PORT
    value: "3550"
  - key: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: DISABLE_TRACING
    value: "1"
  - name: DISABLE_PROFILE
    value: "1"
  - name: DISABLE_DEBUGGER
    value: "1"

servicePort: 3550
